language: node_js
node_js:
  - "5.2.0"
before_script:
  - npm install -g gulp
script: gulp

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
